"""Update relationship of teacher and subject

Revision ID: 5988945e4f03
Revises: 9cddd97c519b
Create Date: 2025-01-19 14:34:53.132594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5988945e4f03'
down_revision: Union[str, None] = '9cddd97c519b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
