"""Update relationship of marks, students and subjects

Revision ID: cabec15fd133
Revises: 5988945e4f03
Create Date: 2025-01-19 14:50:23.737444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabec15fd133'
down_revision: Union[str, None] = '5988945e4f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('marks', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'marks', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'subject_id')
    op.drop_column('marks', 'student_id')
    # ### end Alembic commands ###
